import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Sparkles } from "lucide-react";
import { SiteHeader } from "@/components/SiteHeader";

export const Route = createFileRoute("/examples")({
  head: () => ({
    meta: [
      { title: "Examples — SpecAI" },
      { name: "description", content: "Real specs generated by SpecAI: SaaS, marketplaces, mobile apps, internal tools, and more." },
      { property: "og:title", content: "Examples — SpecAI" },
      { property: "og:description", content: "See real PRDs, architectures, and design systems generated by SpecAI." },
    ],
  }),
  component: ExamplesPage,
});

const EXAMPLES = [
  {
    tag: "SaaS",
    title: "Async Standup Bot",
    desc: "Slack-native standup tool with AI summaries and weekly digests for distributed teams.",
    stack: ["React", "Node", "Postgres", "OpenAI"],
    accent: "from-primary/20 to-transparent",
  },
  {
    tag: "Marketplace",
    title: "Local Skills Exchange",
    desc: "Two-sided marketplace for trading skills (design, coding, music) with reputation scoring.",
    stack: ["Next.js", "Supabase", "Stripe Connect"],
    accent: "from-emerald-500/20 to-transparent",
  },
  {
    tag: "Mobile",
    title: "Habit Garden",
    desc: "Gamified habit tracker where streaks grow a virtual garden. iOS-first with Apple Health.",
    stack: ["Expo", "RN", "Convex"],
    accent: "from-lime-400/20 to-transparent",
  },
  {
    tag: "Internal",
    title: "Ops Console",
    desc: "Internal admin panel with role-based access, audit logs, and CSV bulk actions.",
    stack: ["Remix", "Prisma", "Postgres"],
    accent: "from-primary/15 to-transparent",
  },
  {
    tag: "AI",
    title: "Meeting Memory",
    desc: "Records meetings, extracts action items, syncs to Linear/Jira, indexes for semantic search.",
    stack: ["Next.js", "Pinecone", "Whisper"],
    accent: "from-teal-400/20 to-transparent",
  },
  {
    tag: "Edu",
    title: "Code Quiz Hub",
    desc: "Spaced repetition quizzes for engineering interviews. Daily streaks and team leaderboards.",
    stack: ["SvelteKit", "Drizzle", "Turso"],
    accent: "from-primary/20 to-transparent",
  },
];

function ExamplesPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <SiteHeader />
      <main className="flex-1">
        <section className="relative overflow-hidden border-b border-border/50">
          <div className="absolute inset-0 bg-grid opacity-30 [mask-image:radial-gradient(ellipse_at_center,black,transparent_70%)]" />
          <div className="relative mx-auto max-w-6xl px-6 pt-20 pb-14 text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-border bg-surface/60 text-xs text-muted-foreground mb-6">
              <Sparkles className="w-3 h-3 text-primary" />
              Real outputs · Real ideas
            </div>
            <h1 className="font-display text-5xl md:text-6xl font-bold tracking-tight">
              Specs that <span className="gradient-text">shipped.</span>
            </h1>
            <p className="mt-5 text-lg text-muted-foreground max-w-2xl mx-auto">
              Browse real project specs generated with SpecAI. Steal a structure, remix a stack, ship faster.
            </p>
          </div>
        </section>

        <section className="py-16">
          <div className="mx-auto max-w-6xl px-6">
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
              {EXAMPLES.map((ex, i) => (
                <article
                  key={i}
                  className="group relative overflow-hidden rounded-2xl border border-border bg-surface/40 hover:border-primary/40 transition-all hover:-translate-y-1 duration-300"
                >
                  <div className={`absolute inset-0 bg-gradient-to-br ${ex.accent} opacity-0 group-hover:opacity-100 transition-opacity`} />
                  <div className="relative p-6">
                    <div className="flex items-center justify-between mb-4">
                      <span className="text-[10px] font-mono uppercase tracking-wider px-2 py-1 rounded-md bg-accent text-accent-foreground border border-primary/20">
                        {ex.tag}
                      </span>
                      <span className="text-[10px] font-mono text-muted-foreground">7 docs</span>
                    </div>
                    <h3 className="font-display text-xl font-semibold mb-2 group-hover:text-primary transition-colors">
                      {ex.title}
                    </h3>
                    <p className="text-sm text-muted-foreground leading-relaxed mb-4">{ex.desc}</p>
                    <div className="flex flex-wrap gap-1.5">
                      {ex.stack.map((s) => (
                        <span key={s} className="text-[10px] font-mono px-2 py-1 rounded bg-background border border-border text-muted-foreground">
                          {s}
                        </span>
                      ))}
                    </div>
                  </div>
                </article>
              ))}
            </div>

            <div className="mt-16 text-center">
              <Link
                to="/build"
                className="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-primary text-primary-foreground font-medium glow-primary hover:scale-[1.02] transition-transform"
              >
                Generate your own
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
