/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SrsGeneratorRouteImport } from './routes/srs-generator'
import { Route as SoftwareArchitectureGeneratorRouteImport } from './routes/software-architecture-generator'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrdGeneratorRouteImport } from './routes/prd-generator'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DesignDocumentGeneratorRouteImport } from './routes/design-document-generator'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuildRouteImport } from './routes/build'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ApiDocumentationGeneratorRouteImport } from './routes/api-documentation-generator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SrsGeneratorRoute = SrsGeneratorRouteImport.update({
  id: '/srs-generator',
  path: '/srs-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareArchitectureGeneratorRoute =
  SoftwareArchitectureGeneratorRouteImport.update({
    id: '/software-architecture-generator',
    path: '/software-architecture-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdGeneratorRoute = PrdGeneratorRouteImport.update({
  id: '/prd-generator',
  path: '/prd-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignDocumentGeneratorRoute = DesignDocumentGeneratorRouteImport.update({
  id: '/design-document-generator',
  path: '/design-document-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentationGeneratorRoute =
  ApiDocumentationGeneratorRouteImport.update({
    id: '/api-documentation-generator',
    path: '/api-documentation-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-documentation-generator': typeof ApiDocumentationGeneratorRoute
  '/billing': typeof BillingRoute
  '/build': typeof BuildRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/design-document-generator': typeof DesignDocumentGeneratorRoute
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/prd-generator': typeof PrdGeneratorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/software-architecture-generator': typeof SoftwareArchitectureGeneratorRoute
  '/srs-generator': typeof SrsGeneratorRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-documentation-generator': typeof ApiDocumentationGeneratorRoute
  '/billing': typeof BillingRoute
  '/build': typeof BuildRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/design-document-generator': typeof DesignDocumentGeneratorRoute
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/prd-generator': typeof PrdGeneratorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/software-architecture-generator': typeof SoftwareArchitectureGeneratorRoute
  '/srs-generator': typeof SrsGeneratorRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-documentation-generator': typeof ApiDocumentationGeneratorRoute
  '/billing': typeof BillingRoute
  '/build': typeof BuildRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/design-document-generator': typeof DesignDocumentGeneratorRoute
  '/docs': typeof DocsRoute
  '/examples': typeof ExamplesRoute
  '/prd-generator': typeof PrdGeneratorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/software-architecture-generator': typeof SoftwareArchitectureGeneratorRoute
  '/srs-generator': typeof SrsGeneratorRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-documentation-generator'
    | '/billing'
    | '/build'
    | '/contact'
    | '/cookies'
    | '/design-document-generator'
    | '/docs'
    | '/examples'
    | '/prd-generator'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/software-architecture-generator'
    | '/srs-generator'
    | '/terms'
    | '/welcome'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-documentation-generator'
    | '/billing'
    | '/build'
    | '/contact'
    | '/cookies'
    | '/design-document-generator'
    | '/docs'
    | '/examples'
    | '/prd-generator'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/software-architecture-generator'
    | '/srs-generator'
    | '/terms'
    | '/welcome'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/api-documentation-generator'
    | '/billing'
    | '/build'
    | '/contact'
    | '/cookies'
    | '/design-document-generator'
    | '/docs'
    | '/examples'
    | '/prd-generator'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/software-architecture-generator'
    | '/srs-generator'
    | '/terms'
    | '/welcome'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocumentationGeneratorRoute: typeof ApiDocumentationGeneratorRoute
  BillingRoute: typeof BillingRoute
  BuildRoute: typeof BuildRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DesignDocumentGeneratorRoute: typeof DesignDocumentGeneratorRoute
  DocsRoute: typeof DocsRoute
  ExamplesRoute: typeof ExamplesRoute
  PrdGeneratorRoute: typeof PrdGeneratorRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RefundRoute: typeof RefundRoute
  SoftwareArchitectureGeneratorRoute: typeof SoftwareArchitectureGeneratorRoute
  SrsGeneratorRoute: typeof SrsGeneratorRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/srs-generator': {
      id: '/srs-generator'
      path: '/srs-generator'
      fullPath: '/srs-generator'
      preLoaderRoute: typeof SrsGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-architecture-generator': {
      id: '/software-architecture-generator'
      path: '/software-architecture-generator'
      fullPath: '/software-architecture-generator'
      preLoaderRoute: typeof SoftwareArchitectureGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prd-generator': {
      id: '/prd-generator'
      path: '/prd-generator'
      fullPath: '/prd-generator'
      preLoaderRoute: typeof PrdGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-document-generator': {
      id: '/design-document-generator'
      path: '/design-document-generator'
      fullPath: '/design-document-generator'
      preLoaderRoute: typeof DesignDocumentGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-documentation-generator': {
      id: '/api-documentation-generator'
      path: '/api-documentation-generator'
      fullPath: '/api-documentation-generator'
      preLoaderRoute: typeof ApiDocumentationGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocumentationGeneratorRoute: ApiDocumentationGeneratorRoute,
  BillingRoute: BillingRoute,
  BuildRoute: BuildRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DesignDocumentGeneratorRoute: DesignDocumentGeneratorRoute,
  DocsRoute: DocsRoute,
  ExamplesRoute: ExamplesRoute,
  PrdGeneratorRoute: PrdGeneratorRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RefundRoute: RefundRoute,
  SoftwareArchitectureGeneratorRoute: SoftwareArchitectureGeneratorRoute,
  SrsGeneratorRoute: SrsGeneratorRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
